config/routes.rb
Rails.application.routes.draw do

  get 'initiatives/index'

  resources :pins
  devise_for :users
root 'home#index'

get 'home/required_tasks'
get 'home/announcements'
get 'home/development'
get 'initiatives/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def announcements
  end

  def development
  end

  def required_tasks
  end
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  def index
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_footer.html.erb
<hr class="featurette-divider">
 <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>Contact Us</strong>
                    </h4>
                    <p>1234 NYC Street <br>
                    New York, NY 10007</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (718) 127-4567</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:name@example.com">name@example.com</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-vimeo fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                    <p class="text-muted">Copyright &copy; Principals Weekly 2017</p>
                </div>
            </div>
        </div>
    </footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Principals Weekly", root_path, class:"navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-right nav-pills">

      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "Required Tasks", home_required_tasks_path %></li>
        <li><%= link_to "Initiatives", initiatives_index_path%></li>
        <li><%= link_to "Announcements", home_announcements_path%></li>
        <li><%= link_to "Development", home_development_path%></li>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret">
          </span></a>
            <ul class="dropdown-menu">
            <% if user_signed_in? %>
                <li><%= link_to "Edit Profile", edit_user_registration_path%></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>

       <% else %> 
        <li><%= link_to "Login", new_user_session_path%></li>
        <li><%= link_to "Join", new_user_registration_path%></li>
       <% end %>
       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/announcements.html.erb
<h1>Announcements</h1>
<p>Here are some announcements</p>

app/views/home/development.html.erb
<h1>Professional Development and Learning Opportunities</h1>
<p> Here are some new professional development and learning opportunities!</p>

app/views/home/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/assets/warning.jpg" alt="...">
      <div class="carousel-caption">
        <h2>Notice</h2>
        <p>Due to the upcoming snow storm, all public schools will be closed on February 9, 2017</p>
      </div>
    </div>


    <div class="item">
      <div class="slider-size">
        <img src="/assets/nycdoe.jpg" alt="...">
      </div>
        <div class="carousel-caption">
          <h2>This is the Second caption</h2>
          <p>Details regarding slide 2</p>
        </div>

    </div>


     <div class="item">
      <img src="/assets/bus1.jpg" alt="...">
      <div class="carousel-caption">
        <h2>Important announcement regarding public busses</h2>
        <p>Details regarding slide 3</p>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<hr class="featurette-divider">

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="featurette-heading">A letter From Our Chancellor</h3>
  </div>
 
 <div class="panel-body">
    <img class="img-circle img-responsive pull-right" src="http://schools.nyc.gov/NR/rdonlyres/3D71E8E0-0376-48F9-95BE-C112E01AF9D4/168761/Carmen_official2.jpg">

    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ultrices enim non libero consectetur cursus. Sed mauris magna, vehicula non maximus eget, porttitor sed mauris. Duis imperdiet est eu dapibus laoreet. Vestibulum ultricies elementum tellus. Nulla sed semper lectus. Vestibulum aliquam nec lectus ut auctor. Sed ipsum augue, finibus nec ex at, suscipit porttitor turpis. Morbi viverra augue nibh, non facilisis odio condimentum sit amet. Vivamus ut urna et erat vehicula ullamcorper. Ut dui metus, cursus iaculis feugiat quis, luctus vel velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ultrices enim non libero consectetur cursus. Sed mauris magna, vehicula non maximus eget, porttitor sed mauris. Duis imperdiet est eu dapibus laoreet. Vestibulum ultricies elementum tellus... </p>
    </div>
    <div class="panel-footer">
      <button type="button" class="btn btn-primary">read more</button>
      <h4 class="pull-right"> Date Posted: 8/3/2017</h4>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row">
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://www.educationpioneers.org/sites/default/files/styles/blog__small/public/New-York-City-Department-of-Education_0.jpg?itok=Gpz_VgJ8" alt="">
                <h2>June Regents / RCT Exam</h2>
                <p>enim non libero consectetur cursus. Sed mauris magna, vehicula non maximus eget, porttitor sed mauris. Duis imperdiet est eu dapibus laoreet. Vestibulum ultricies elementum tellus. Nulla sed semper lectus. Vestibulum aliquam nec lectus ut auctor. Sed ipsum augue, finibus nec ex at, suscipit porttitor turpis. Morbi viverra augue nibh, non facilisis odio condimentum sit amet. Vivamus...</p>
                <button type="button" class="btn btn-primary">Read More</button>

            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://source.colostate.edu/wp-content/uploads/2016/05/summerfoodprogram-300x300.jpg" alt="">
                <h2>Summer Meals Program</h2>
                <p>enim non libero consectetur cursus. Sed mauris magna, vehicula non maximus eget, porttitor sed mauris. Duis imperdiet est eu dapibus laoreet. Vestibulum ultricies elementum tellus. Nulla sed semper lectus. Vestibulum aliquam nec lectus ut auctor. Sed ipsum augue, finibus nec ex at, suscipit porttitor turpis. Morbi viverra augue nibh, non facilisis odio condimentum sit amet. Vivamus...</p>
                <button type="button" class="btn btn-primary">Read More</button>

            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://www.deacademichouse.com/wp-content/uploads/education-300x300.png" alt="">
                <h2>Academic Policy Training</h2>
                <p>enim non libero consectetur cursus. Sed mauris magna, vehicula non maximus eget, porttitor sed mauris. Duis imperdiet est eu dapibus laoreet. Vestibulum ultricies elementum tellus. Nulla sed semper lectus. Vestibulum aliquam nec lectus ut auctor. Sed ipsum augue, finibus nec ex at, suscipit porttitor turpis. Morbi viverra augue nibh, non facilisis odio condimentum sit amet. Vivamus...</p>
                <button type="button" class="btn btn-primary">Read More</button>

            </div>
        </div>


 

app/views/home/required_tasks.html.erb
<h1>required tasks</h1>
<p>Check back here for required tasks!</p>

app/views/initiatives/index.html.erb
<h1>Initiatives</h1>
<p>Here is a list of some DOE initiatives!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Principals Weekly</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/2cf8943d57.js"></script>
  </head>

  <body>

  <%= render 'home/header'%>
<div class = 'container'>

<% flash.each do |name,msg| %>
  <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

    <%= yield %>
     
    <%=render 'home/footer'%>
</div>    
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for(pin) do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit',class:"btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>Editing Pin</h1></div>

  <div class="panel-body">
	<%= render 'form', pin: @pin %>
	</div>

<div class="panel-footer">
	<%= link_to 'Show', @pin %> |
	<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>New Pin</h1></div>
  <div class="panel-body">

<%= render 'form', pin: @pin %>

</div>
 <div class="panel-footer">
<%= link_to 'Back', pins_path %>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>